#!/usr/bin/env python3
"""Bake the UI fonts into src/ui_font_data.h.

The renderer draws no text of its own; the game paints its menus and HUD into a
CPU canvas (src/ui_draw.c), so the glyphs are baked here as 8-bit coverage
bitmaps and compiled in. Nothing is loaded from disk at runtime, which keeps
the menus working from any working directory and on Windows builds.

Fonts: Liberation Sans Bold / Liberation Serif Bold (SIL Open Font License).
"""
from PIL import Image, ImageDraw, ImageFont
import os, sys

FONTS = [
    ("UI_FONT_SMALL", "/usr/share/fonts/liberation/LiberationSans-Bold.ttf", 18),
    ("UI_FONT_BODY", "/usr/share/fonts/liberation/LiberationSans-Bold.ttf", 26),
    ("UI_FONT_HEADING", "/usr/share/fonts/liberation/LiberationSerif-Bold.ttf", 40),
    ("UI_FONT_TITLE", "/usr/share/fonts/liberation/LiberationSerif-Bold.ttf", 72),
]
FIRST, LAST = 32, 126

out = []
out.append("/* Generated by tools/build_ui_font.py -- do not edit. */\n#pragma once\n#include <stdint.h>\n")
tables = []
for name, path, size in FONTS:
    font = ImageFont.truetype(path, size)
    ascent, descent = font.getmetrics()
    line = ascent + descent
    pixels = bytearray()
    glyphs = []
    for c in range(FIRST, LAST + 1):
        ch = chr(c)
        advance = int(round(font.getlength(ch)))
        left, top, right, bottom = font.getbbox(ch)
        left = min(left, 0)
        w = max(right - left, 1)
        img = Image.new("L", (w, line), 0)
        ImageDraw.Draw(img).text((-left, 0), ch, font=font, fill=255)
        glyphs.append((len(pixels), w, left, advance))
        pixels += img.tobytes()
    lower = name.lower()
    out.append(f"static const uint8_t {lower}_pixels[{len(pixels)}] = {{")
    row = []
    for i, b in enumerate(pixels):
        row.append(str(b))
        if len(row) == 40:
            out.append(",".join(row) + ",")
            row = []
    if row:
        out.append(",".join(row))
    out.append("};")
    out.append(f"static const UiGlyph {lower}_glyphs[{LAST - FIRST + 1}] = {{")
    for off, w, left, adv in glyphs:
        out.append(f"\t{{{off}u, {w}, {left}, {adv}}},")
    out.append("};")
    tables.append((name, lower, line, ascent))

header = out[0]
body = "\n".join(out[1:])
defs = ("typedef struct\n{\n\tuint32_t offset; /* into the font's pixel array */\n"
        "\tint16_t width, left, advance;\n} UiGlyph;\n\n"
        "typedef struct\n{\n\tconst uint8_t *pixels;\n\tconst UiGlyph *glyphs;\n"
        "\tint line_height, ascent;\n} UiFontData;\n\n"
        f"#define UI_FONT_FIRST_CHAR {FIRST}\n#define UI_FONT_LAST_CHAR {LAST}\n\n")
fonts = "static const UiFontData ui_fonts[] = {\n" + "".join(
    f"\t{{{lower}_pixels, {lower}_glyphs, {line}, {ascent}}}, /* {name} */\n"
    for name, lower, line, ascent in tables) + "};\n"
dst = os.path.join(os.path.dirname(__file__), "..", "src", "ui_font_data.h")
with open(dst, "w") as f:
    f.write(header + defs + body + "\n\n" + fonts)
print("wrote", dst)
