#!/usr/bin/env python3
"""Extract a heightmap from the swissALTI3D data and emit a C array.

Reads one 1 km x 1 km swissALTI3D tile (0.5 m, 2000x2000 float samples),
area-averages it down to a coarse GRID_N x GRID_N grid, and writes a
copy-paste-ready C snippet to ``heightarr.txt`` next to this script.

The snippet drops straight into ``src/terrain.h``.

Only Pillow is required (the tiles are plain float32 TIFFs).
"""

import math
import os

from PIL import Image

Image.MAX_IMAGE_PIXELS = None  # the tiles are big but trusted

# --- configuration ---------------------------------------------------------
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

# Centre tile of the 1x3 km strip: 1 km x 1 km near Baeregg / Grindelwald.
TILE = os.path.join(ROOT, "alps-data", "swissalti3d_2025_2647-1160_0.5m.tif")
TILE_SPAN_M = 1000.0          # each swisstopo tile covers 1 km x 1 km
GRID_N = 128                  # output resolution (GRID_N x GRID_N samples)
PER_LINE = 12                 # array entries per source line

OUT = os.path.join(HERE, "heightarr.txt")


def load_elevations(path):
    """Return (width, height, flat list of float elevations, row-major)."""
    im = Image.open(path)
    if im.mode != "F":
        raise SystemExit(f"expected float TIFF (mode 'F'), got {im.mode!r}")
    w, h = im.size
    # get_flattened_data() on newer Pillow, getdata() on older; both row-major.
    getter = getattr(im, "get_flattened_data", im.getdata)
    return w, h, list(getter())


def area_downsample(src, w, h, n):
    """Area-average src (w*h float, row-major) down to n*n, row-major.

    Cell (i, j) averages every source pixel whose centre falls in the
    integer box [x0,x1) x [y0,y1); this works for any n, not just divisors
    of w/h. Non-finite samples (nodata) are skipped inside each cell.
    """
    out = [0.0] * (n * n)
    for j in range(n):
        y0, y1 = j * h // n, (j + 1) * h // n
        for i in range(n):
            x0, x1 = i * w // n, (i + 1) * w // n
            total, count = 0.0, 0
            for y in range(y0, y1):
                base = y * w
                for x in range(x0, x1):
                    v = src[base + x]
                    if math.isfinite(v):
                        total += v
                        count += 1
            out[j * n + i] = total / count if count else float("nan")
    return out


def format_c(values, n, spacing):
    lines = []
    lines.append(
        "/* Auto-generated by tools/extract_height_data.py -- DO NOT EDIT BY HAND.\n"
        "   Source: swissALTI3D 2025, tile 2647-1160, 0.5 m, EPSG:2056 / LN02.\n"
        "   Region: 1 km x 1 km near Baeregg / Lower Grindelwald Glacier.\n"
        f"   {n} x {n} samples, {spacing:.4f} m horizontal spacing, heights in metres. */"
    )
    lines.append(f"#define TERRAIN_GRID_N    {n}")
    lines.append(f"#define TERRAIN_SPACING_M {spacing:.4f}f")
    lines.append("static const float TERRAIN_HEIGHTMAP[TERRAIN_GRID_N * TERRAIN_GRID_N] = {")
    total = n * n
    for start in range(0, total, PER_LINE):
        chunk = values[start:start + PER_LINE]
        row = " ".join(f"{v:.2f}f," for v in chunk)
        lines.append("    " + row)
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    w, h, src = load_elevations(TILE)
    print(f"loaded {TILE} ({w}x{h})")
    grid = area_downsample(src, w, h, GRID_N)
    spacing = TILE_SPAN_M / GRID_N
    lo, hi = min(grid), max(grid)
    print(f"downsampled to {GRID_N}x{GRID_N}, spacing {spacing:.4f} m, "
          f"elevation {lo:.1f}..{hi:.1f} m")
    with open(OUT, "w") as f:
        f.write(format_c(grid, GRID_N, spacing))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
